# Generated by Django 5.0 on 2024-01-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=30)),
                ('anio_fundacion', models.IntegerField(max_length=5)),
                ('num_parques', models.IntegerField(max_length=7)),
                ('num_monumentos', models.IntegerField(max_length=7)),
                ('presupuesto_anual', models.FloatField(max_length=30)),
                ('clima', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parroquia', models.IntegerField(max_length=30)),
                ('distrito', models.CharField(max_length=30)),
                ('anio_creacion', models.IntegerField(max_length=7)),
                ('num_barrios', models.IntegerField(max_length=7)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.ciudad')),
            ],
        ),
    ]
