# Generated by Django 5.0 on 2024-01-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='nombre_parroquia',
            field=models.CharField(max_length=30),
        ),
    ]
