# Generated by Django 5.0 on 2024-01-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_alter_parroquia_nombre_parroquia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='anio_fundacion',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='num_monumentos',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='num_parques',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='presupuesto_anual',
        ),
        migrations.RemoveField(
            model_name='parroquia',
            name='anio_creacion',
        ),
        migrations.RemoveField(
            model_name='parroquia',
            name='num_barrios',
        ),
    ]
