# Generated by Django 5.0 on 2024-01-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_remove_ciudad_anio_fundacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='anio_fundacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='num_monumentos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='num_parques',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='presupuesto_anual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='anio_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='num_barrios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
